travis:
  secure:
    BINSTAR_TOKEN: Z8UC02TkmJvxAQ4nnLcHR2Hc9RYogYo7FyknITOEi/1sVq3/XLfyOUSrwRsIQvfRlet6pdcZQPHVt4+hRbVZrLtbfK33yU7Fhlhvw4xTLPF7GsRBCBjL2gZ3J3ntgDUrgPynEpJnc8kCjPmj5I3lpQZTF54iYb43i0xsPC6xoWCJ9yN9V4mt76DrsW8jPJeSYCuUhZ943gFC43bwGRvGA9rsSxkYEVosnDVHGFdcKL+nhqB+zbDTWdfJAjbbbsDjknJRKPY2NUyf4iZrT5D+9bNoMWGUcH9sIzMPHzzhwrCGl91sClgZoe/gIabOnwXI0sv1Kl2jVaYUaAdYrBD+oOWMKtjKXtxU5n2lDjFUqtaYpq+a5KC0tpnroCjhhOZU4J4bKC/Y1g5Bf6DmHsGrugyCsGZl/T2IJ6t9qaWCj/ajpA4oVd+P80rvxrfXV54NbtUHY2ojN9FiZl+fIrpgiSC7ykwSmf3sugqgBuH2eezaGPEvEMJa3qd2mhHfAnpCxE9/LVUe6Vp7uftGlaXAVyPT/1+jzTGyDJqOWfTSDWUweny+JM7nyJfRXiPmFJLpkCa/hHUxpzoCW/4y/SKGJmBcUwk8ou2NzkyU6iZ/KZfMo0ew4Umv3DPEHZv6j3wAhVE4Hh0YCs2k24S6Z4uiyO0M2wTtHSGckwjWaRMmSRk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
