travis:
  secure:
    BINSTAR_TOKEN: k4K8HQ+9B5FhCqFFbCT0m6z+yUt1ng4b0pL+DmU6Lk/PBfnVwMdMksXSuIAbBBDJ7tJt2SjWH0mLd6k63SGA7GnUHnS5OoMyvY458Y0BGbldnINo3uUhuB7DMk/WZ/NcQN6G+UmAYCaglZ1aw4dd1kR4NAbsTLqwlyffMQdzcmIfWfHzXj1jGaE/81Uk2y79UJgvOuxi6x00tw9HrTUPWqDbAcWEnHtJ0pMzWBbRMxW8O4SLG/BGWVO0sqAJdOvCUyH2rY2WkbZZ0tcLt10FKo9tvrqS6skN7os6MRWKyDBs0eUYwdWZYKmsxEwJ64Z/mK4r/MuARHpvJiLOE+3B29eV6ZtLC/z2hnGSg1nAmUqVYcXj8Zhu5a8T4G9xTFa5I0nuZZEIGLn55vtofFxirouPdSSZGRP+blZBTYD9aDI1NruNrMOBCzc/SoevGx0jtjEn7P4XM1A/KgXLpQj1UXI2F0orbSK8Ta1zats1MvNrtgcxlKe0qgFpWtnoou9h/C95XriNZg+hCrhNJN740tK/e0geDv/QnAJWl4ECDevRWKRJtRRXlctipdsG8g4FRbE1pXZ2O05y2gmJJ7VXDRfxMNC6paXa1weNKcGOyLvU+mHw4jupxDIq9OSDhWzMKRNWbvbtskkDTxBDJ6ejrE/gqf10gPAWTKIy8rdvdik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
